logging:
  level:
    com.nbclass: ERROR
    tk.mybatis: ERROR
    org.springframework: ERROR
  file: log/zblog-admin.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zb-blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Abc523179414
  redis:
    host: localhost
    port: 6379
    password: Abc523179414